name: Build Enigma

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"

      - name: Setup Swift static SDK
        run: |
          swift sdk install https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz \
            --checksum 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6
            
      - name: Build release
        run: |
          cd core-cloud-enigma
          swift build -c release \
            --swift-sdk x86_64-swift-linux-musl \
            -Xswiftc -cross-module-optimization 
            
      - name: Create artifacts
        run: |
          mkdir result
          mv core-cloud-enigma/.build/release/CoreCloudEnigma result/CoreCloudEnigma_release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CoreCloudEnigma
          path: result
          
